spring.application.name=salud
spring.data.mongodb.uri=mongodb+srv://alejandro:notomarelsolesdecomunistas@clusterapphealth.txt3g.mongodb.net/ClusterAppHealth
server.port=${PORT:8080}
jwt.secret=unaClaveMuySeguraDe32CaracteresOMas
jwt.expiration=86400000